import React from 'react';
import { useQuery } from '@apollo/client';
import { ApolloClientProvider } from '../components/ApolloClientProvider';
import { Launch } from '../types';
import { GET_LAUNCHES_QUERY } from '../components/ApolloClientProvider';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Home = () => {
  debugger
  const { loading, error, data } = useQuery(GET_LAUNCHES_QUERY);

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error :(</p>;

  return (
    <ApolloClientProvider>
      <div>
        <h1>SpaceX Launches</h1>
        <div>
          {data.launchesPast.map((launch: Launch) => (
            <a key={launch.id} href={launch.links.video_link}>
              <h3>{launch.mission_name}</h3>
              <p>
                <strong>Launch Date:</strong>{' '}
                {new Date(launch.launch_date_local).toLocaleDateString('en-US')}
              </p>
            </a>
          ))}
        </div>
      </div>
    </ApolloClientProvider>
  );
};

export default Home;